#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.expand_path("../../lib", __FILE__)

require "neovim"
require "fileutils"
require "tempfile"
require File.expand_path("../../spec/support.rb", __FILE__)

nvim = Neovim.executable.path
root = File.expand_path("../..", __FILE__)
vader = File.join(root, "vendor/vader.vim")
specs = File.join(root, "spec/acceptance/*_spec.vim")
vimrc = File.join(root, "spec/acceptance/runtime/init.vim")
rp_manifest = File.join(root, "spec/acceptance/runtime/rplugin.vim")
argv = [nvim, "--headless", "-u", vimrc]
exitstatus = 0

FileUtils.rm_f(rp_manifest)
at_exit { FileUtils.rm_f(rp_manifest) }

system(
  {"NVIM_RPLUGIN_MANIFEST" => rp_manifest},
  *argv, "+silent UpdateRemotePlugins", "+qa!"
)

exit($?.exitstatus) unless $?.success?

Dir.glob(specs) do |vader_spec|
  Tempfile.open("vader.out") do |tmp|
    Dir.chdir(root) do
      system(
        {"VADER_OUTPUT_FILE" => tmp.path, "NVIM_RPLUGIN_MANIFEST" => rp_manifest},
        *argv, "+Vader! #{vader_spec}"
      )
    end

    if $?.success?
      puts "[✔] #{vader_spec}"
    else
      exitstatus = $?.exitstatus
      IO.copy_stream(tmp, $stderr)
      puts "[✘] #{vader_spec}"
    end
  end
end

if exitstatus == 0
  puts "[✔] Acceptance tests passed."
else
  puts "[✘] Acceptance tests failed."
end

exit(exitstatus)
