#!/usr/bin/env ruby

$:.unshift File.expand_path("../../lib", __FILE__)

require "neovim"
require "pp"

nvim_exe = ENV.fetch("NVIM_EXECUTABLE", "nvim")
session = Neovim::Session.child([nvim_exe, "-u", "NONE", "-n"])
pp session.request(:vim_get_api_info)
